"""Compile upstream compatibility assets into DLL-resident resources; never extract at runtime."""

import argparse
import json
from pathlib import Path
import re


def collect(root: Path):
    resources = []
    seen = set()
    for path in sorted(root.rglob("*")):
        if not path.is_file() or path.suffix.lower() not in (".ini", ".lua"):
            continue
        relative = path.relative_to(root)
        if len(relative.parts) < 2:
            raise ValueError(f"Resource has no profile: {relative}")
        profile, name = relative.parts[0], Path(*relative.parts[1:]).as_posix()
        identity = (profile.lower(), name.lower())
        if identity in seen:
            raise ValueError(f"Duplicate resource: {relative}")
        seen.add(identity)
        # Text normalization also makes output independent of Git's checkout line endings.
        contents = path.read_text(encoding="utf-8-sig").encode("utf-8")
        if b"\0" in contents:
            raise ValueError(f"NUL in text resource: {relative}")
        resources.append((profile, name, contents))
    if not resources:
        raise ValueError("No compatibility resources found")
    return resources


def load_builds(path: Path, resources):
    manifest = json.loads(path.read_text(encoding="utf-8"))
    if manifest.get("schemaVersion") != 1 or not isinstance(manifest.get("builds"), list):
        raise ValueError("Invalid compatibility build manifest")
    profiles = {profile for profile, _, _ in resources}
    seen = set()
    builds = []
    for build in manifest["builds"]:
        if not isinstance(build, dict):
            raise ValueError("Each build must be an object")
        executable, digest, profile = (build.get(key, "") for key in ("executable", "sha256", "profile"))
        if not all(isinstance(value, str) for value in (executable, digest, profile)):
            raise ValueError("Build fields must be strings")
        if not executable.lower().endswith(".exe") or any(c in executable for c in '/\\:'):
            raise ValueError("Executable must be a basename ending in .exe")
        if not re.fullmatch(r"[0-9a-fA-F]{64}", digest) or profile not in profiles:
            raise ValueError("Build must identify a SHA-256 and an existing profile")
        identity = (executable.lower(), digest.lower())
        if identity in seen:
            raise ValueError(f"Duplicate build: {executable}")
        seen.add(identity)
        builds.append((executable, digest.lower(), profile))
    return sorted(builds)


def generate(root: Path, manifest: Path) -> str:
    resources = collect(root)
    builds = load_builds(manifest, resources)
    lines = ['// Generated by embed_compatibility.py. Do not edit.', '#include <Compatibility/Catalog.hpp>',
             '#include <array>', 'namespace RC::Compatibility {', 'namespace {']
    for index, (_, _, contents) in enumerate(resources):
        # Byte initializers avoid MSVC's string-literal length limit and source encoding dependence.
        lines.append(f'const char data_{index}[] = {{')
        for start in range(0, len(contents), 24):
            lines.append(','.join(f"'\\x{byte:02x}'" for byte in contents[start:start + 24]) + ',')
        lines.append("'\\0'};")
    lines.append(f'const std::array<Resource, {len(resources)}> resources = {{{{')
    for index, (profile, path, contents) in enumerate(resources):
        lines.append(f'{{{json.dumps(profile)}, {json.dumps(path)}, {{data_{index}, {len(contents)}}}}},')
    lines.append('}};')
    lines.append(f'const std::array<Build, {len(builds)}> builds = {{{{')
    for executable, digest, profile in builds:
        lines.append('{' + ', '.join(json.dumps(value) for value in (executable, digest, profile)) + '},')
    lines.extend(['}};', '}', 'auto builtin_catalog() -> Catalog { return {resources, builds}; }', '}'])
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root', type=Path, required=True)
    parser.add_argument('--manifest', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    output = generate(args.root, args.manifest)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    if not args.output.exists() or args.output.read_text(encoding='utf-8') != output:
        args.output.write_text(output, encoding='utf-8', newline='\n')
