find_package(Python3 REQUIRED COMPONENTS Interpreter)
set(UE4SS_COMPATIBILITY_ROOT "${CMAKE_CURRENT_LIST_DIR}/../assets/CustomGameConfigs")
set(UE4SS_COMPATIBILITY_GENERATOR "${CMAKE_CURRENT_LIST_DIR}/../tools/embed_compatibility.py")
file(GLOB_RECURSE UE4SS_COMPATIBILITY_INPUTS CONFIGURE_DEPENDS
    "${UE4SS_COMPATIBILITY_ROOT}/*.ini" "${UE4SS_COMPATIBILITY_ROOT}/*.lua")
set(UE4SS_COMPATIBILITY_SOURCE "${CMAKE_CURRENT_BINARY_DIR}/generated/BuiltinCompatibility.cpp")
add_custom_command(
    OUTPUT "${UE4SS_COMPATIBILITY_SOURCE}"
    COMMAND "${Python3_EXECUTABLE}" "${UE4SS_COMPATIBILITY_GENERATOR}"
        --root "${UE4SS_COMPATIBILITY_ROOT}"
        --manifest "${UE4SS_COMPATIBILITY_ROOT}/validated-builds.json"
        --output "${UE4SS_COMPATIBILITY_SOURCE}"
    DEPENDS ${UE4SS_COMPATIBILITY_INPUTS} "${UE4SS_COMPATIBILITY_ROOT}/validated-builds.json" "${UE4SS_COMPATIBILITY_GENERATOR}"
    VERBATIM
)
